### ISSUE TITLE
Car despawn rates

### ISSUE THREAD

**Issue by demutigerdrache** [42MonthsAfter/wiki#1]
My car despawned 2 days after getting it, may we please get an extension?

**Comment by BnYrB** [comment]
Need to know what car and what server?

**Comment by BnYrB** [comment]
friendly ping? Any details available here?

**Comment by BnYrB** [comment]
@demutigerdrache

**Comment by demutigerdrache** [comment]
Sorry I don't get pings on here, 42 months after pve, vaz_2109
