### ISSUE TITLE
Update to car details

### ISSUE THREAD

**Issue by bluecollarboysgaming** [42MonthsAfter/wiki#12]
I was running an experiment with wild bill on abandoned.  had him drive a 6x6 spawned in vehicle by me.  then we froze out.  then we took the red olga from trader and i drove with him as passenger and it glitched him and the i couldn't exit the vehicle.

**Comment by BnYrB** [comment]
I'm thinking this is not a car or mod issue but a ping issue. 

Did you get an error anything when you froze? My guess is that high speeds and high pings are causing these crashes. Your ping is over 350 at times, haven't checked billy bobs, but if a group is in a car, the player with the worst ping will impact everyone. The game has trouble understanding where everyone is suppose to be and that can cause client side crashing from what I can tell.
