### ISSUE TITLE
Red falcon cases

### ISSUE THREAD

**Issue by bluecollarboysgaming** [42MonthsAfter/wiki#3]
Tested it.  Red falcon cases will despawn.  not sure if thats just what it is?

**Comment by BnYrB** [comment]
put a fix into place with the noon restart, should take care of it. Let me know if it doesn't

**Comment by BnYrB** [comment]
Did this resolve this @bluecollarboysgaming ???

**Comment by bluecollarboysgaming** [comment]
I'll have to buy a case and find out.
