### ISSUE TITLE
car bug

### ISSUE THREAD

**Issue by Toobigdaddy** [42MonthsAfter/wiki#5]
character name
xxbamxbam510
server 
42 months after on your own
 The situation was on the 1/12/2023 i found a car and fixed took it to the holler and this morning and took it to Paris island got there started looting and put some weapons' and guile suites in the trunk and then drove little bit down south where more of the barracks where went out and started looting more came back logged and logged back in and it took me like back to where i previous was and ran to the last place were the car was and it was gone

**Comment by BnYrB** [comment]
what car was it? And what color?
