### ISSUE TITLE
Car locks 42monthsafter pve

### ISSUE THREAD

**Issue by demutigerdrache** [42MonthsAfter/wiki#8]
My buddy put to many numbers in the lock setting it up now I can't get the vehicle to unlock after he gave me it, and the code for it. I don't know if there is anything yall can do but yeah.

**Comment by BnYrB** [comment]
sadly not much we can do about that other than delete the car and start again. Is there a bunch of stuff in the car storage?

**Comment by demutigerdrache** [comment]
Yeah we just moved bases
